[package]
name = "xfix-that-touch"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["derive"]}
dialoguer = "0.12.0"
glob = "0.3.3"
home = "0.5.12"
regex = "1.12.2"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.149"
