name: test-and-build

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_test_and_build:
    name: Lint, Test and Build demex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - uses: Swatinem/rust-cache@v2

      - name: cargo check
        run: cargo check --all-features

      - name: cargo test
        run: cargo test --all-features

      - name: cargo build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demex
          path: target/release/xfix-that-touch
